---
resource_pools:
  - name: small
    network: openvpn
    stemcell: (( grab meta.stemcell ))

    cloud_properties: {}

compilation:
  network: openvpn
  workers: 2
  reuse_compilation_vms: true

  cloud_properties: {}

jobs:
  - name: openvpn
    resource_pool: small
